ALTER TABLE oconnor.purchases ADD COLUMN IF NOT EXISTS pcard INT DEFAULT 0;
ALTER TABLE oconnor.quotes ADD COLUMN IF NOT EXISTS grant_id VARCHAR(255);
ALTER TABLE oconnor.vendors ADD COLUMN IF NOT EXISTS mds INT DEFAULT 0;
